spring.application.name=back

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate cria tableas do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no console o SQL que o Hibernate está executando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true